//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.235
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace BaseMap.RoutingServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.ObjectModel.ObservableCollection<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoutingServiceReference.RoutingWebServiceSoap")]
    public interface RoutingWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(BaseMap.RoutingServiceReference.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        BaseMap.RoutingServiceReference.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetRouting", ReplyAction="*")]
        System.IAsyncResult BeginGetRouting(BaseMap.RoutingServiceReference.GetRoutingRequest request, System.AsyncCallback callback, object asyncState);
        
        BaseMap.RoutingServiceReference.GetRoutingResponse EndGetRouting(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetBeginRoad", ReplyAction="*")]
        System.IAsyncResult BeginGetBeginRoad(BaseMap.RoutingServiceReference.GetBeginRoadRequest request, System.AsyncCallback callback, object asyncState);
        
        BaseMap.RoutingServiceReference.GetBeginRoadResponse EndGetBeginRoad(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetLastRoad", ReplyAction="*")]
        System.IAsyncResult BeginGetLastRoad(BaseMap.RoutingServiceReference.GetLastRoadRequest request, System.AsyncCallback callback, object asyncState);
        
        BaseMap.RoutingServiceReference.GetLastRoadResponse EndGetLastRoad(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetBarrierRoad", ReplyAction="*")]
        System.IAsyncResult BeginGetBarrierRoad(BaseMap.RoutingServiceReference.GetBarrierRoadRequest request, System.AsyncCallback callback, object asyncState);
        
        BaseMap.RoutingServiceReference.GetBarrierRoadResponse EndGetBarrierRoad(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UpdatePassable", ReplyAction="*")]
        System.IAsyncResult BeginUpdatePassable(int source, int target, int passable, System.AsyncCallback callback, object asyncState);
        
        void EndUpdatePassable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/QueryRealRoads", ReplyAction="*")]
        System.IAsyncResult BeginQueryRealRoads(BaseMap.RoutingServiceReference.QueryRealRoadsRequest request, System.AsyncCallback callback, object asyncState);
        
        BaseMap.RoutingServiceReference.QueryRealRoadsResponse EndQueryRealRoads(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/updateLength", ReplyAction="*")]
        System.IAsyncResult BeginupdateLength(System.AsyncCallback callback, object asyncState);
        
        void EndupdateLength(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/updatePassableToT", ReplyAction="*")]
        System.IAsyncResult BeginupdatePassableToT(System.AsyncCallback callback, object asyncState);
        
        void EndupdatePassableToT(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BaseMap.RoutingServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BaseMap.RoutingServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoutingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRouting", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.GetRoutingRequestBody Body;
        
        public GetRoutingRequest() {
        }
        
        public GetRoutingRequest(BaseMap.RoutingServiceReference.GetRoutingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoutingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string layer;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int begin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int last;
        
        public GetRoutingRequestBody() {
        }
        
        public GetRoutingRequestBody(string layer, int begin, int last) {
            this.layer = layer;
            this.begin = begin;
            this.last = last;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoutingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoutingResponse", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.GetRoutingResponseBody Body;
        
        public GetRoutingResponse() {
        }
        
        public GetRoutingResponse(BaseMap.RoutingServiceReference.GetRoutingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoutingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BaseMap.RoutingServiceReference.ArrayOfString GetRoutingResult;
        
        public GetRoutingResponseBody() {
        }
        
        public GetRoutingResponseBody(BaseMap.RoutingServiceReference.ArrayOfString GetRoutingResult) {
            this.GetRoutingResult = GetRoutingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeginRoadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeginRoad", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.GetBeginRoadRequestBody Body;
        
        public GetBeginRoadRequest() {
        }
        
        public GetBeginRoadRequest(BaseMap.RoutingServiceReference.GetBeginRoadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBeginRoadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double lg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double lt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double ditMini;
        
        public GetBeginRoadRequestBody() {
        }
        
        public GetBeginRoadRequestBody(double lg, double lt, double ditMini) {
            this.lg = lg;
            this.lt = lt;
            this.ditMini = ditMini;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeginRoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeginRoadResponse", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.GetBeginRoadResponseBody Body;
        
        public GetBeginRoadResponse() {
        }
        
        public GetBeginRoadResponse(BaseMap.RoutingServiceReference.GetBeginRoadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBeginRoadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BaseMap.RoutingServiceReference.ArrayOfString GetBeginRoadResult;
        
        public GetBeginRoadResponseBody() {
        }
        
        public GetBeginRoadResponseBody(BaseMap.RoutingServiceReference.ArrayOfString GetBeginRoadResult) {
            this.GetBeginRoadResult = GetBeginRoadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastRoadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastRoad", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.GetLastRoadRequestBody Body;
        
        public GetLastRoadRequest() {
        }
        
        public GetLastRoadRequest(BaseMap.RoutingServiceReference.GetLastRoadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLastRoadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double lg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double lt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double ditMini;
        
        public GetLastRoadRequestBody() {
        }
        
        public GetLastRoadRequestBody(double lg, double lt, double ditMini) {
            this.lg = lg;
            this.lt = lt;
            this.ditMini = ditMini;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastRoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastRoadResponse", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.GetLastRoadResponseBody Body;
        
        public GetLastRoadResponse() {
        }
        
        public GetLastRoadResponse(BaseMap.RoutingServiceReference.GetLastRoadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLastRoadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BaseMap.RoutingServiceReference.ArrayOfString GetLastRoadResult;
        
        public GetLastRoadResponseBody() {
        }
        
        public GetLastRoadResponseBody(BaseMap.RoutingServiceReference.ArrayOfString GetLastRoadResult) {
            this.GetLastRoadResult = GetLastRoadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBarrierRoadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBarrierRoad", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.GetBarrierRoadRequestBody Body;
        
        public GetBarrierRoadRequest() {
        }
        
        public GetBarrierRoadRequest(BaseMap.RoutingServiceReference.GetBarrierRoadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBarrierRoadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double lg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double lt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double ditMini;
        
        public GetBarrierRoadRequestBody() {
        }
        
        public GetBarrierRoadRequestBody(double lg, double lt, double ditMini) {
            this.lg = lg;
            this.lt = lt;
            this.ditMini = ditMini;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBarrierRoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBarrierRoadResponse", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.GetBarrierRoadResponseBody Body;
        
        public GetBarrierRoadResponse() {
        }
        
        public GetBarrierRoadResponse(BaseMap.RoutingServiceReference.GetBarrierRoadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBarrierRoadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BaseMap.RoutingServiceReference.ArrayOfString GetBarrierRoadResult;
        
        public GetBarrierRoadResponseBody() {
        }
        
        public GetBarrierRoadResponseBody(BaseMap.RoutingServiceReference.ArrayOfString GetBarrierRoadResult) {
            this.GetBarrierRoadResult = GetBarrierRoadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRealRoadsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryRealRoads", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.QueryRealRoadsRequestBody Body;
        
        public QueryRealRoadsRequest() {
        }
        
        public QueryRealRoadsRequest(BaseMap.RoutingServiceReference.QueryRealRoadsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryRealRoadsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string layer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string leve;
        
        public QueryRealRoadsRequestBody() {
        }
        
        public QueryRealRoadsRequestBody(string layer, string leve) {
            this.layer = layer;
            this.leve = leve;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRealRoadsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryRealRoadsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BaseMap.RoutingServiceReference.QueryRealRoadsResponseBody Body;
        
        public QueryRealRoadsResponse() {
        }
        
        public QueryRealRoadsResponse(BaseMap.RoutingServiceReference.QueryRealRoadsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryRealRoadsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BaseMap.RoutingServiceReference.ArrayOfString QueryRealRoadsResult;
        
        public QueryRealRoadsResponseBody() {
        }
        
        public QueryRealRoadsResponseBody(BaseMap.RoutingServiceReference.ArrayOfString QueryRealRoadsResult) {
            this.QueryRealRoadsResult = QueryRealRoadsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RoutingWebServiceSoapChannel : BaseMap.RoutingServiceReference.RoutingWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRoutingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRoutingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public BaseMap.RoutingServiceReference.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((BaseMap.RoutingServiceReference.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBeginRoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBeginRoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public BaseMap.RoutingServiceReference.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((BaseMap.RoutingServiceReference.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLastRoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLastRoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public BaseMap.RoutingServiceReference.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((BaseMap.RoutingServiceReference.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBarrierRoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBarrierRoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public BaseMap.RoutingServiceReference.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((BaseMap.RoutingServiceReference.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryRealRoadsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QueryRealRoadsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public BaseMap.RoutingServiceReference.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((BaseMap.RoutingServiceReference.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoutingWebServiceSoapClient : System.ServiceModel.ClientBase<BaseMap.RoutingServiceReference.RoutingWebServiceSoap>, BaseMap.RoutingServiceReference.RoutingWebServiceSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRoutingDelegate;
        
        private EndOperationDelegate onEndGetRoutingDelegate;
        
        private System.Threading.SendOrPostCallback onGetRoutingCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetBeginRoadDelegate;
        
        private EndOperationDelegate onEndGetBeginRoadDelegate;
        
        private System.Threading.SendOrPostCallback onGetBeginRoadCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLastRoadDelegate;
        
        private EndOperationDelegate onEndGetLastRoadDelegate;
        
        private System.Threading.SendOrPostCallback onGetLastRoadCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetBarrierRoadDelegate;
        
        private EndOperationDelegate onEndGetBarrierRoadDelegate;
        
        private System.Threading.SendOrPostCallback onGetBarrierRoadCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdatePassableDelegate;
        
        private EndOperationDelegate onEndUpdatePassableDelegate;
        
        private System.Threading.SendOrPostCallback onUpdatePassableCompletedDelegate;
        
        private BeginOperationDelegate onBeginQueryRealRoadsDelegate;
        
        private EndOperationDelegate onEndQueryRealRoadsDelegate;
        
        private System.Threading.SendOrPostCallback onQueryRealRoadsCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateLengthDelegate;
        
        private EndOperationDelegate onEndupdateLengthDelegate;
        
        private System.Threading.SendOrPostCallback onupdateLengthCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdatePassableToTDelegate;
        
        private EndOperationDelegate onEndupdatePassableToTDelegate;
        
        private System.Threading.SendOrPostCallback onupdatePassableToTCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public RoutingWebServiceSoapClient() {
        }
        
        public RoutingWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutingWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<GetRoutingCompletedEventArgs> GetRoutingCompleted;
        
        public event System.EventHandler<GetBeginRoadCompletedEventArgs> GetBeginRoadCompleted;
        
        public event System.EventHandler<GetLastRoadCompletedEventArgs> GetLastRoadCompleted;
        
        public event System.EventHandler<GetBarrierRoadCompletedEventArgs> GetBarrierRoadCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdatePassableCompleted;
        
        public event System.EventHandler<QueryRealRoadsCompletedEventArgs> QueryRealRoadsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> updateLengthCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> updatePassableToTCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BaseMap.RoutingServiceReference.RoutingWebServiceSoap.BeginHelloWorld(BaseMap.RoutingServiceReference.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            BaseMap.RoutingServiceReference.HelloWorldRequest inValue = new BaseMap.RoutingServiceReference.HelloWorldRequest();
            inValue.Body = new BaseMap.RoutingServiceReference.HelloWorldRequestBody();
            return ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaseMap.RoutingServiceReference.HelloWorldResponse BaseMap.RoutingServiceReference.RoutingWebServiceSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndHelloWorld(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.HelloWorldResponse retVal = ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BaseMap.RoutingServiceReference.RoutingWebServiceSoap.BeginGetRouting(BaseMap.RoutingServiceReference.GetRoutingRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRouting(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetRouting(string layer, int begin, int last, System.AsyncCallback callback, object asyncState) {
            BaseMap.RoutingServiceReference.GetRoutingRequest inValue = new BaseMap.RoutingServiceReference.GetRoutingRequest();
            inValue.Body = new BaseMap.RoutingServiceReference.GetRoutingRequestBody();
            inValue.Body.layer = layer;
            inValue.Body.begin = begin;
            inValue.Body.last = last;
            return ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).BeginGetRouting(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaseMap.RoutingServiceReference.GetRoutingResponse BaseMap.RoutingServiceReference.RoutingWebServiceSoap.EndGetRouting(System.IAsyncResult result) {
            return base.Channel.EndGetRouting(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private BaseMap.RoutingServiceReference.ArrayOfString EndGetRouting(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.GetRoutingResponse retVal = ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).EndGetRouting(result);
            return retVal.Body.GetRoutingResult;
        }
        
        private System.IAsyncResult OnBeginGetRouting(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string layer = ((string)(inValues[0]));
            int begin = ((int)(inValues[1]));
            int last = ((int)(inValues[2]));
            return this.BeginGetRouting(layer, begin, last, callback, asyncState);
        }
        
        private object[] OnEndGetRouting(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.ArrayOfString retVal = this.EndGetRouting(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRoutingCompleted(object state) {
            if ((this.GetRoutingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRoutingCompleted(this, new GetRoutingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRoutingAsync(string layer, int begin, int last) {
            this.GetRoutingAsync(layer, begin, last, null);
        }
        
        public void GetRoutingAsync(string layer, int begin, int last, object userState) {
            if ((this.onBeginGetRoutingDelegate == null)) {
                this.onBeginGetRoutingDelegate = new BeginOperationDelegate(this.OnBeginGetRouting);
            }
            if ((this.onEndGetRoutingDelegate == null)) {
                this.onEndGetRoutingDelegate = new EndOperationDelegate(this.OnEndGetRouting);
            }
            if ((this.onGetRoutingCompletedDelegate == null)) {
                this.onGetRoutingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRoutingCompleted);
            }
            base.InvokeAsync(this.onBeginGetRoutingDelegate, new object[] {
                        layer,
                        begin,
                        last}, this.onEndGetRoutingDelegate, this.onGetRoutingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BaseMap.RoutingServiceReference.RoutingWebServiceSoap.BeginGetBeginRoad(BaseMap.RoutingServiceReference.GetBeginRoadRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBeginRoad(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetBeginRoad(double lg, double lt, double ditMini, System.AsyncCallback callback, object asyncState) {
            BaseMap.RoutingServiceReference.GetBeginRoadRequest inValue = new BaseMap.RoutingServiceReference.GetBeginRoadRequest();
            inValue.Body = new BaseMap.RoutingServiceReference.GetBeginRoadRequestBody();
            inValue.Body.lg = lg;
            inValue.Body.lt = lt;
            inValue.Body.ditMini = ditMini;
            return ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).BeginGetBeginRoad(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaseMap.RoutingServiceReference.GetBeginRoadResponse BaseMap.RoutingServiceReference.RoutingWebServiceSoap.EndGetBeginRoad(System.IAsyncResult result) {
            return base.Channel.EndGetBeginRoad(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private BaseMap.RoutingServiceReference.ArrayOfString EndGetBeginRoad(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.GetBeginRoadResponse retVal = ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).EndGetBeginRoad(result);
            return retVal.Body.GetBeginRoadResult;
        }
        
        private System.IAsyncResult OnBeginGetBeginRoad(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double lg = ((double)(inValues[0]));
            double lt = ((double)(inValues[1]));
            double ditMini = ((double)(inValues[2]));
            return this.BeginGetBeginRoad(lg, lt, ditMini, callback, asyncState);
        }
        
        private object[] OnEndGetBeginRoad(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.ArrayOfString retVal = this.EndGetBeginRoad(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBeginRoadCompleted(object state) {
            if ((this.GetBeginRoadCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBeginRoadCompleted(this, new GetBeginRoadCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBeginRoadAsync(double lg, double lt, double ditMini) {
            this.GetBeginRoadAsync(lg, lt, ditMini, null);
        }
        
        public void GetBeginRoadAsync(double lg, double lt, double ditMini, object userState) {
            if ((this.onBeginGetBeginRoadDelegate == null)) {
                this.onBeginGetBeginRoadDelegate = new BeginOperationDelegate(this.OnBeginGetBeginRoad);
            }
            if ((this.onEndGetBeginRoadDelegate == null)) {
                this.onEndGetBeginRoadDelegate = new EndOperationDelegate(this.OnEndGetBeginRoad);
            }
            if ((this.onGetBeginRoadCompletedDelegate == null)) {
                this.onGetBeginRoadCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBeginRoadCompleted);
            }
            base.InvokeAsync(this.onBeginGetBeginRoadDelegate, new object[] {
                        lg,
                        lt,
                        ditMini}, this.onEndGetBeginRoadDelegate, this.onGetBeginRoadCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BaseMap.RoutingServiceReference.RoutingWebServiceSoap.BeginGetLastRoad(BaseMap.RoutingServiceReference.GetLastRoadRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLastRoad(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetLastRoad(double lg, double lt, double ditMini, System.AsyncCallback callback, object asyncState) {
            BaseMap.RoutingServiceReference.GetLastRoadRequest inValue = new BaseMap.RoutingServiceReference.GetLastRoadRequest();
            inValue.Body = new BaseMap.RoutingServiceReference.GetLastRoadRequestBody();
            inValue.Body.lg = lg;
            inValue.Body.lt = lt;
            inValue.Body.ditMini = ditMini;
            return ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).BeginGetLastRoad(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaseMap.RoutingServiceReference.GetLastRoadResponse BaseMap.RoutingServiceReference.RoutingWebServiceSoap.EndGetLastRoad(System.IAsyncResult result) {
            return base.Channel.EndGetLastRoad(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private BaseMap.RoutingServiceReference.ArrayOfString EndGetLastRoad(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.GetLastRoadResponse retVal = ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).EndGetLastRoad(result);
            return retVal.Body.GetLastRoadResult;
        }
        
        private System.IAsyncResult OnBeginGetLastRoad(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double lg = ((double)(inValues[0]));
            double lt = ((double)(inValues[1]));
            double ditMini = ((double)(inValues[2]));
            return this.BeginGetLastRoad(lg, lt, ditMini, callback, asyncState);
        }
        
        private object[] OnEndGetLastRoad(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.ArrayOfString retVal = this.EndGetLastRoad(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLastRoadCompleted(object state) {
            if ((this.GetLastRoadCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLastRoadCompleted(this, new GetLastRoadCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLastRoadAsync(double lg, double lt, double ditMini) {
            this.GetLastRoadAsync(lg, lt, ditMini, null);
        }
        
        public void GetLastRoadAsync(double lg, double lt, double ditMini, object userState) {
            if ((this.onBeginGetLastRoadDelegate == null)) {
                this.onBeginGetLastRoadDelegate = new BeginOperationDelegate(this.OnBeginGetLastRoad);
            }
            if ((this.onEndGetLastRoadDelegate == null)) {
                this.onEndGetLastRoadDelegate = new EndOperationDelegate(this.OnEndGetLastRoad);
            }
            if ((this.onGetLastRoadCompletedDelegate == null)) {
                this.onGetLastRoadCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLastRoadCompleted);
            }
            base.InvokeAsync(this.onBeginGetLastRoadDelegate, new object[] {
                        lg,
                        lt,
                        ditMini}, this.onEndGetLastRoadDelegate, this.onGetLastRoadCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BaseMap.RoutingServiceReference.RoutingWebServiceSoap.BeginGetBarrierRoad(BaseMap.RoutingServiceReference.GetBarrierRoadRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBarrierRoad(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetBarrierRoad(double lg, double lt, double ditMini, System.AsyncCallback callback, object asyncState) {
            BaseMap.RoutingServiceReference.GetBarrierRoadRequest inValue = new BaseMap.RoutingServiceReference.GetBarrierRoadRequest();
            inValue.Body = new BaseMap.RoutingServiceReference.GetBarrierRoadRequestBody();
            inValue.Body.lg = lg;
            inValue.Body.lt = lt;
            inValue.Body.ditMini = ditMini;
            return ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).BeginGetBarrierRoad(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaseMap.RoutingServiceReference.GetBarrierRoadResponse BaseMap.RoutingServiceReference.RoutingWebServiceSoap.EndGetBarrierRoad(System.IAsyncResult result) {
            return base.Channel.EndGetBarrierRoad(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private BaseMap.RoutingServiceReference.ArrayOfString EndGetBarrierRoad(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.GetBarrierRoadResponse retVal = ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).EndGetBarrierRoad(result);
            return retVal.Body.GetBarrierRoadResult;
        }
        
        private System.IAsyncResult OnBeginGetBarrierRoad(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double lg = ((double)(inValues[0]));
            double lt = ((double)(inValues[1]));
            double ditMini = ((double)(inValues[2]));
            return this.BeginGetBarrierRoad(lg, lt, ditMini, callback, asyncState);
        }
        
        private object[] OnEndGetBarrierRoad(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.ArrayOfString retVal = this.EndGetBarrierRoad(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBarrierRoadCompleted(object state) {
            if ((this.GetBarrierRoadCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBarrierRoadCompleted(this, new GetBarrierRoadCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBarrierRoadAsync(double lg, double lt, double ditMini) {
            this.GetBarrierRoadAsync(lg, lt, ditMini, null);
        }
        
        public void GetBarrierRoadAsync(double lg, double lt, double ditMini, object userState) {
            if ((this.onBeginGetBarrierRoadDelegate == null)) {
                this.onBeginGetBarrierRoadDelegate = new BeginOperationDelegate(this.OnBeginGetBarrierRoad);
            }
            if ((this.onEndGetBarrierRoadDelegate == null)) {
                this.onEndGetBarrierRoadDelegate = new EndOperationDelegate(this.OnEndGetBarrierRoad);
            }
            if ((this.onGetBarrierRoadCompletedDelegate == null)) {
                this.onGetBarrierRoadCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBarrierRoadCompleted);
            }
            base.InvokeAsync(this.onBeginGetBarrierRoadDelegate, new object[] {
                        lg,
                        lt,
                        ditMini}, this.onEndGetBarrierRoadDelegate, this.onGetBarrierRoadCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BaseMap.RoutingServiceReference.RoutingWebServiceSoap.BeginUpdatePassable(int source, int target, int passable, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdatePassable(source, target, passable, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void BaseMap.RoutingServiceReference.RoutingWebServiceSoap.EndUpdatePassable(System.IAsyncResult result) {
            base.Channel.EndUpdatePassable(result);
        }
        
        private System.IAsyncResult OnBeginUpdatePassable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int source = ((int)(inValues[0]));
            int target = ((int)(inValues[1]));
            int passable = ((int)(inValues[2]));
            return ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).BeginUpdatePassable(source, target, passable, callback, asyncState);
        }
        
        private object[] OnEndUpdatePassable(System.IAsyncResult result) {
            ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).EndUpdatePassable(result);
            return null;
        }
        
        private void OnUpdatePassableCompleted(object state) {
            if ((this.UpdatePassableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdatePassableCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdatePassableAsync(int source, int target, int passable) {
            this.UpdatePassableAsync(source, target, passable, null);
        }
        
        public void UpdatePassableAsync(int source, int target, int passable, object userState) {
            if ((this.onBeginUpdatePassableDelegate == null)) {
                this.onBeginUpdatePassableDelegate = new BeginOperationDelegate(this.OnBeginUpdatePassable);
            }
            if ((this.onEndUpdatePassableDelegate == null)) {
                this.onEndUpdatePassableDelegate = new EndOperationDelegate(this.OnEndUpdatePassable);
            }
            if ((this.onUpdatePassableCompletedDelegate == null)) {
                this.onUpdatePassableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdatePassableCompleted);
            }
            base.InvokeAsync(this.onBeginUpdatePassableDelegate, new object[] {
                        source,
                        target,
                        passable}, this.onEndUpdatePassableDelegate, this.onUpdatePassableCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BaseMap.RoutingServiceReference.RoutingWebServiceSoap.BeginQueryRealRoads(BaseMap.RoutingServiceReference.QueryRealRoadsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQueryRealRoads(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginQueryRealRoads(string layer, string leve, System.AsyncCallback callback, object asyncState) {
            BaseMap.RoutingServiceReference.QueryRealRoadsRequest inValue = new BaseMap.RoutingServiceReference.QueryRealRoadsRequest();
            inValue.Body = new BaseMap.RoutingServiceReference.QueryRealRoadsRequestBody();
            inValue.Body.layer = layer;
            inValue.Body.leve = leve;
            return ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).BeginQueryRealRoads(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaseMap.RoutingServiceReference.QueryRealRoadsResponse BaseMap.RoutingServiceReference.RoutingWebServiceSoap.EndQueryRealRoads(System.IAsyncResult result) {
            return base.Channel.EndQueryRealRoads(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private BaseMap.RoutingServiceReference.ArrayOfString EndQueryRealRoads(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.QueryRealRoadsResponse retVal = ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).EndQueryRealRoads(result);
            return retVal.Body.QueryRealRoadsResult;
        }
        
        private System.IAsyncResult OnBeginQueryRealRoads(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string layer = ((string)(inValues[0]));
            string leve = ((string)(inValues[1]));
            return this.BeginQueryRealRoads(layer, leve, callback, asyncState);
        }
        
        private object[] OnEndQueryRealRoads(System.IAsyncResult result) {
            BaseMap.RoutingServiceReference.ArrayOfString retVal = this.EndQueryRealRoads(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQueryRealRoadsCompleted(object state) {
            if ((this.QueryRealRoadsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryRealRoadsCompleted(this, new QueryRealRoadsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryRealRoadsAsync(string layer, string leve) {
            this.QueryRealRoadsAsync(layer, leve, null);
        }
        
        public void QueryRealRoadsAsync(string layer, string leve, object userState) {
            if ((this.onBeginQueryRealRoadsDelegate == null)) {
                this.onBeginQueryRealRoadsDelegate = new BeginOperationDelegate(this.OnBeginQueryRealRoads);
            }
            if ((this.onEndQueryRealRoadsDelegate == null)) {
                this.onEndQueryRealRoadsDelegate = new EndOperationDelegate(this.OnEndQueryRealRoads);
            }
            if ((this.onQueryRealRoadsCompletedDelegate == null)) {
                this.onQueryRealRoadsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryRealRoadsCompleted);
            }
            base.InvokeAsync(this.onBeginQueryRealRoadsDelegate, new object[] {
                        layer,
                        leve}, this.onEndQueryRealRoadsDelegate, this.onQueryRealRoadsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BaseMap.RoutingServiceReference.RoutingWebServiceSoap.BeginupdateLength(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateLength(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void BaseMap.RoutingServiceReference.RoutingWebServiceSoap.EndupdateLength(System.IAsyncResult result) {
            base.Channel.EndupdateLength(result);
        }
        
        private System.IAsyncResult OnBeginupdateLength(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).BeginupdateLength(callback, asyncState);
        }
        
        private object[] OnEndupdateLength(System.IAsyncResult result) {
            ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).EndupdateLength(result);
            return null;
        }
        
        private void OnupdateLengthCompleted(object state) {
            if ((this.updateLengthCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateLengthCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateLengthAsync() {
            this.updateLengthAsync(null);
        }
        
        public void updateLengthAsync(object userState) {
            if ((this.onBeginupdateLengthDelegate == null)) {
                this.onBeginupdateLengthDelegate = new BeginOperationDelegate(this.OnBeginupdateLength);
            }
            if ((this.onEndupdateLengthDelegate == null)) {
                this.onEndupdateLengthDelegate = new EndOperationDelegate(this.OnEndupdateLength);
            }
            if ((this.onupdateLengthCompletedDelegate == null)) {
                this.onupdateLengthCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateLengthCompleted);
            }
            base.InvokeAsync(this.onBeginupdateLengthDelegate, null, this.onEndupdateLengthDelegate, this.onupdateLengthCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BaseMap.RoutingServiceReference.RoutingWebServiceSoap.BeginupdatePassableToT(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdatePassableToT(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void BaseMap.RoutingServiceReference.RoutingWebServiceSoap.EndupdatePassableToT(System.IAsyncResult result) {
            base.Channel.EndupdatePassableToT(result);
        }
        
        private System.IAsyncResult OnBeginupdatePassableToT(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).BeginupdatePassableToT(callback, asyncState);
        }
        
        private object[] OnEndupdatePassableToT(System.IAsyncResult result) {
            ((BaseMap.RoutingServiceReference.RoutingWebServiceSoap)(this)).EndupdatePassableToT(result);
            return null;
        }
        
        private void OnupdatePassableToTCompleted(object state) {
            if ((this.updatePassableToTCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updatePassableToTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updatePassableToTAsync() {
            this.updatePassableToTAsync(null);
        }
        
        public void updatePassableToTAsync(object userState) {
            if ((this.onBeginupdatePassableToTDelegate == null)) {
                this.onBeginupdatePassableToTDelegate = new BeginOperationDelegate(this.OnBeginupdatePassableToT);
            }
            if ((this.onEndupdatePassableToTDelegate == null)) {
                this.onEndupdatePassableToTDelegate = new EndOperationDelegate(this.OnEndupdatePassableToT);
            }
            if ((this.onupdatePassableToTCompletedDelegate == null)) {
                this.onupdatePassableToTCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdatePassableToTCompleted);
            }
            base.InvokeAsync(this.onBeginupdatePassableToTDelegate, null, this.onEndupdatePassableToTDelegate, this.onupdatePassableToTCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override BaseMap.RoutingServiceReference.RoutingWebServiceSoap CreateChannel() {
            return new RoutingWebServiceSoapClientChannel(this);
        }
        
        private class RoutingWebServiceSoapClientChannel : ChannelBase<BaseMap.RoutingServiceReference.RoutingWebServiceSoap>, BaseMap.RoutingServiceReference.RoutingWebServiceSoap {
            
            public RoutingWebServiceSoapClientChannel(System.ServiceModel.ClientBase<BaseMap.RoutingServiceReference.RoutingWebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(BaseMap.RoutingServiceReference.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public BaseMap.RoutingServiceReference.HelloWorldResponse EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                BaseMap.RoutingServiceReference.HelloWorldResponse _result = ((BaseMap.RoutingServiceReference.HelloWorldResponse)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRouting(BaseMap.RoutingServiceReference.GetRoutingRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetRouting", _args, callback, asyncState);
                return _result;
            }
            
            public BaseMap.RoutingServiceReference.GetRoutingResponse EndGetRouting(System.IAsyncResult result) {
                object[] _args = new object[0];
                BaseMap.RoutingServiceReference.GetRoutingResponse _result = ((BaseMap.RoutingServiceReference.GetRoutingResponse)(base.EndInvoke("GetRouting", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetBeginRoad(BaseMap.RoutingServiceReference.GetBeginRoadRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetBeginRoad", _args, callback, asyncState);
                return _result;
            }
            
            public BaseMap.RoutingServiceReference.GetBeginRoadResponse EndGetBeginRoad(System.IAsyncResult result) {
                object[] _args = new object[0];
                BaseMap.RoutingServiceReference.GetBeginRoadResponse _result = ((BaseMap.RoutingServiceReference.GetBeginRoadResponse)(base.EndInvoke("GetBeginRoad", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLastRoad(BaseMap.RoutingServiceReference.GetLastRoadRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLastRoad", _args, callback, asyncState);
                return _result;
            }
            
            public BaseMap.RoutingServiceReference.GetLastRoadResponse EndGetLastRoad(System.IAsyncResult result) {
                object[] _args = new object[0];
                BaseMap.RoutingServiceReference.GetLastRoadResponse _result = ((BaseMap.RoutingServiceReference.GetLastRoadResponse)(base.EndInvoke("GetLastRoad", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetBarrierRoad(BaseMap.RoutingServiceReference.GetBarrierRoadRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetBarrierRoad", _args, callback, asyncState);
                return _result;
            }
            
            public BaseMap.RoutingServiceReference.GetBarrierRoadResponse EndGetBarrierRoad(System.IAsyncResult result) {
                object[] _args = new object[0];
                BaseMap.RoutingServiceReference.GetBarrierRoadResponse _result = ((BaseMap.RoutingServiceReference.GetBarrierRoadResponse)(base.EndInvoke("GetBarrierRoad", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdatePassable(int source, int target, int passable, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = source;
                _args[1] = target;
                _args[2] = passable;
                System.IAsyncResult _result = base.BeginInvoke("UpdatePassable", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdatePassable(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdatePassable", _args, result);
            }
            
            public System.IAsyncResult BeginQueryRealRoads(BaseMap.RoutingServiceReference.QueryRealRoadsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("QueryRealRoads", _args, callback, asyncState);
                return _result;
            }
            
            public BaseMap.RoutingServiceReference.QueryRealRoadsResponse EndQueryRealRoads(System.IAsyncResult result) {
                object[] _args = new object[0];
                BaseMap.RoutingServiceReference.QueryRealRoadsResponse _result = ((BaseMap.RoutingServiceReference.QueryRealRoadsResponse)(base.EndInvoke("QueryRealRoads", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginupdateLength(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("updateLength", _args, callback, asyncState);
                return _result;
            }
            
            public void EndupdateLength(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("updateLength", _args, result);
            }
            
            public System.IAsyncResult BeginupdatePassableToT(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("updatePassableToT", _args, callback, asyncState);
                return _result;
            }
            
            public void EndupdatePassableToT(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("updatePassableToT", _args, result);
            }
        }
    }
}
